# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1
  - nightly
jobs:
  allow_failures:
  - julia: nightly
  include:
  - os: linux
    julia: 1.0
  - os: linux
    julia: 1
  - os: linux
    julia: nightly
  - os: osx
    julia: 1
  - os: windows
    julia: 1
notifications:
  email: false
